### PR TITLE
added [chi-2, chi-2-gam, mom-chi-2]

### PR DESCRIPTION
**Pull request by kjpetrykowski**
I have added a definition of chi-square distribution and two related theorems.

### CODE REVIEW

**Comment by kjpetrykowski** [comment]
This is my first commit to this repository, so feedback is highly appreciated :)

**Comment by JoramSoch** [comment]
@kjpetrykowski: Dear Kenneth, many thanks for your contribution! I have [integrated your content](https://github.com/StatProofBook/StatProofBook.github.io/commit/43af43a85c482fa426101e18a1e47c4f5f1cba25) into the archive and [added your submissions](https://github.com/StatProofBook/StatProofBook.github.io/commit/1d21f3cb230d2ae0fbba02babf267536010b06a3) to the index pages. I renamed your file shortcuts to adhere to our [naming conventions](https://github.com/StatProofBook/StatProofBook.github.io/wiki/Naming-Conventions). You may check out the above links to see how what other changes I did to your code in order to make it compatible with the StatProofBook.

**Comment by JoramSoch** [comment]
Here's an example using [your definition "chi2"](https://statproofbook.github.io/D/chi2).

### This is how it looked before editing:
V1

### And this is how it looks now:
V2

In other words, one has to be a bit careful with what characters such as `$`, `$$`, `\`, `\\`. Other things are more a matter of taste. For example, you are using `{.}` and `{...}` a lot and sometimes it's not necessary. Besides that, try to be consistent with `\frac{x}{y}` vs. `x/y` within one page and things like that.

**Comment by JoramSoch** [comment]
Content-wise, there are two things left, I think (but they don't have to be done immediately):

- [Definition "chi2"](https://statproofbook.github.io/D/chi2): The probability density function has to be derived from the definition and them moved to a separate [proof "chi2-pdf"](https://statproofbook.github.io/P/chi2-pdf).
- [Proof "chi2-gam"](https://statproofbook.github.io/P/chi2-mom): The last two equations should be extended a bit to make the resultmore transparent. It should also include a definition of the [gamma function](https://en.wikipedia.org/wiki/Gamma_function).

Feel free to implement these changes!

**Comment by kjpetrykowski** [comment]
@JoramSoch: Dear Joram, thank you for your reply! I am sorry for these few bugs, I will adjust my future code to be free of such issues and also implement your suggested changes. Have a nice evening!

**Comment by JoramSoch** [comment]
@kjpetrykowski: No worries! These things happened a lot to me in the beginning. GitHub Pages in combination with MathJax is not as easy as it pretends to be. ;-)

**Pull request merged**
