### PR TITLE
added "bf" and "sddr-bf"

### PR DESCRIPTION
**Pull request by tomfaulkenberry**
This is my first contribution of several I have planned.  But, I wanted to do this one first by itself to make sure I have the workflow down correctly! :)

### CODE REVIEW

**Comment by StatProofBook** [comment]
Hey Tom, excellent first commit! You seem to have read the entire StatProofBook documentation that I've been writing for myself over the past year... :D I don't really know how to edit/modify forein commits either in GitHub.com or in GitHub Desktop, therefore I simply merged everything into master and will adapt a little bit. Then, feel free to update to master and continue adding your content... :)

**Comment by StatProofBook** [comment]
I now did [this commit](https://github.com/StatProofBook/StatProofBook.github.io/commit/3ffb96f700084b19bf2e1080345011b83b0a7f2c) integrating your material. Thanks a lot for your efforts!

**Comment by tomfaulkenberry** [comment]
Thanks @JoramSoch!  I will look forward to more contributions soon.

**Comment by StatProofBook** [comment]
And [with this](https://github.com/StatProofBook/StatProofBook.github.io/commit/af82313b1d118a270001d4e6f1cc5dbf55a67995), you are in the indexes, see:
* [Definition by Author](https://statproofbook.github.io/I/Definition_by_Author)
* [Proof by Author](https://statproofbook.github.io/I/Proof_by_Author)

**Pull request merged**
