### PR TITLE
added section on the covariance matrix of a random vector with a multinomial distribution

### PR DESCRIPTION
**Pull request by adkipnis**
is there a way to preview the whole book after making own changes? The markdown module in VS Code does not allow me to check if e.g. all the links to other chapters are coded correctly...

### CODE REVIEW

**Comment by JoramSoch** [comment]
Yes, it's always tedious to foresee what your changes will look like, esp. with mathematical equations. Technically, the website is a [static page in Jekyll](https://github.com/jekyll/jekyll). So, if you install a [Jekyll page builder](https://jekyllrb.com/docs/installation/), you can generate the project after making changes and see what the pages, links etc. look like.

**Comment by JoramSoch** [comment]
I did a [few corrections](https://github.com/StatProofBook/StatProofBook.github.io/commit/3f6b2ee011a719bb29f4636f9f334427735154d9), some for making it actually work, some more being StatProofBook conventions or matters of taste. By now, everything should look as intended. For the future, I suggest to draft proofs in LaTeX and then transfer them to the proof template (that's how I do it).
mult-cov-after

**Comment by JoramSoch** [comment]
However, I don't understand the transition from the second to the third line. Can you explain that to me?

**Comment by JoramSoch** [comment]
I think I got it now. It was supposed to read like this, right?
mvn-cov-correct

**Comment by adkipnis** [comment]
Yes, my mistake, I had overlooked it since the second term becomes 0 either way. Sorry for the late response, until now I was at the MEG where there was no wifi

**Pull request merged**
