### PR TITLE
add lognormal cdf

### PR DESCRIPTION
**Pull request by majapavlo**

### CODE REVIEW

**Comment by majapavlo** [comment]
cleaned up the previous attempt 🤞

**Comment by majapavlo** [comment]
@JoramSoch I think the update.py step didn't work as expected. It seems to be picking up one of your proofs. Any suggestions on what to do now 🤔

**Comment by JoramSoch** [comment]
@majapavlo: Thanks for trying `ToC.md` and `update.py`! I'm having a look at it now...

**Comment by JoramSoch** [comment]
The error was that you didn't update the Proof ID (starting with "P..."), so that my "ng-nw" and your "lognorm-cdf" were considered the same item. Now that's correct, see [here](https://github.com/StatProofBook/StatProofBook.github.io/commit/a0274f9d4780378331c16c96cb3f1bc332de8736). I should change "update.py" to identify proofs and definitions via their shortcut rather than their ID.

For your information, I've also deleted "norm-cdf" as a source for "lognorm-cdf". I think there's no need to reference other StatProofBook sites as sources, as you can directly reference them in your proof - which I've also added, see [here](https://github.com/StatProofBook/StatProofBook.github.io/commit/6fc21d28392f8b78963a723141728848409d2921).

**Comment by majapavlo** [comment]
@JoramSoch amazing thank you 🙏 ! The last Proof I could find in production was `323`, so I added the _lognorm-cdf_ as `324`, but that was clearly not correct then. Thanks for updating! And yes the direct reference makes sense 👍

**Pull request merged**
