### PR TITLE
Clean definitions and theorems

### PR DESCRIPTION
**Pull request by pitmonticone**

### CODE REVIEW

**Comment by JoramSoch** [comment]
Dear @pitmonticone, thanks for contributing and for your great attention to detail! Did you use some spell checking software or did you find all these errors manually? :)

**Comment by pitmonticone** [comment]
Hi @JoramSoch, 

Thank you very much for the maintenance of such an interesting project. I'm pleased to contribute to a resource that I find valuable. 

To answer your question:
1. I found the repository quite useful and decided that contributing would be a good way to give a bit back.
2. Textual revision and editing are activities I particularly enjoy, especially when I am traveling.
3. While consulting the parts of the content most relevant to me, I took the opportunity to manually correct typos (via smartphone in this case haha). 
4. My contribution is obviously contingent on my available time. Typically, if I manually identify more than $n$ errors—be they in text syntax, text semantics, code syntax, or code semantics—I opt to contribute by: 
   - running a global "find and replace" for all mistakes I've manually found locally;
   - using the default spell-checker to complete the job.
   
Hope it's helpful.

**Comment by pitmonticone** [comment]
By the way @JoramSoch, have you thought about creating a GitHub organisation for this project importing there the relevant repositories currently hosted by this individual account in order to be able to use all the organisation-level functionalities and increase the probability of more contributions? 

Let me know if you're interested. I'd be happy to help if necessary.

**Comment by JoramSoch** [comment]
Dear @pitmonticone, thanks again, very helpful! Re "organization": Maybe yes. I'm going to put this on the todo list (= open an issue in this repository) and will get back to you, if I need help in registering an organisation.

**Pull request merged**
