### PR TITLE
add median minimizes MAE

### PR DESCRIPTION
**Pull request by salbalkus**
As promised, adds a proof that the median minimizes the mean absolute error. Happy to make any other changes or fixes needed upon review.

### CODE REVIEW

**Comment by JoramSoch** [comment]
Hey @salbalkus, many thanks for your new submission! The [proof was integrated](https://github.com/StatProofBook/StatProofBook.github.io/commit/ed68c9a7642f3b3ef37d81eb8232d8db83a75a26). Note: We don't usually link to external sources (e.g. Wikipedia) in the proof text, as this can cause problems with [converting the Website to PDF](https://github.com/StatProofBook/StatProofBookTools/blob/master/write_book.py) (also see [Citing FAQ](https://github.com/StatProofBook/StatProofBook.github.io/wiki/Citing-Conventions#frequently-asked-questions)). It's correct to put those links into the sources which you did just fine.

**Comment by JoramSoch** [comment]
By the way, this is how the proof looked online before I made some changes (e.g. the title is missing, because there was no closing `"` in `topic: "Measures of central tendency`, and the formula crashed, because it used the same label `eq:med-mae-s1` as another equation). Yes, it's very ideosyncratic, but don't worry, this also happens to me all the time. A GitHub page is just not as user-friendly as a Wiki, but it has other advantages... :)

---

**before**:

med-mae_V1

---

**after**:

med-mae_V2

**Comment by salbalkus** [comment]
Thanks @JoramSoch ! I basically just copied over the equations from some personal notes into the .md so many thanks for fixing the equation issue and the links. I'll be sure to avoid external links in the future :+1:

**Comment by JoramSoch** [comment]
Sure! I also prepare my Proofs in LaTeX and then copy them over to Markdown (actually, with the help of [this little script](https://github.com/StatProofBook/StatProofBookTools/blob/master/create_proof.py)).

**Pull request merged**
